import model5, model6, model7, model8


print("MODEL 5")
print("***")
print(model5.run("juneJuly_abs_4.csv"))
print(model5.run("juneJuly_abs_8.csv"))
print(model5.run("juneJuly_abs_12.csv"))
print("***")
print(model5.run("juneJuly_ava_4.csv"))
print(model5.run("juneJuly_ava_8.csv"))
print(model5.run("juneJuly_ava_12.csv"))
print("***")
print(model5.run("juneJuly_c_4.csv"))
print(model5.run("juneJuly_c_8.csv"))
print(model5.run("juneJuly_c_12.csv"))
print("***")
print(model5.run("juneJuly_d_4.csv"))
print(model5.run("juneJuly_d_8.csv"))
print(model5.run("juneJuly_d_12.csv"))

print()

print("MODEL 6")
print("***")
print(model6.run("juneJuly_abs_4.csv"))
print(model6.run("juneJuly_abs_8.csv"))
print(model6.run("juneJuly_abs_12.csv"))
print("***")
print(model6.run("juneJuly_ava_4.csv"))
print(model6.run("juneJuly_ava_8.csv"))
print(model6.run("juneJuly_ava_12.csv"))
print("***")
print(model6.run("juneJuly_c_4.csv"))
print(model6.run("juneJuly_c_8.csv"))
print(model6.run("juneJuly_c_12.csv"))
print("***")
print(model6.run("juneJuly_d_4.csv"))
print(model6.run("juneJuly_d_8.csv"))
print(model6.run("juneJuly_d_12.csv"))

print()

print("MODEL 7")
print("***")
print(model7.run("juneJuly_ava_4.csv"))
print(model7.run("juneJuly_ava_8.csv"))
print(model7.run("juneJuly_ava_12.csv"))
print("***")
print(model7.run("juneJuly_c_4.csv"))
print(model7.run("juneJuly_c_8.csv"))
print(model7.run("juneJuly_c_12.csv"))

print()

print("MODEL 8")
print("***")

print(model8.run("juneJuly_ava_4.csv", 2))
print(model8.run("juneJuly_ava_8.csv", 2))
print(model8.run("juneJuly_ava_12.csv", 2))
print("***")
print(model8.run("juneJuly_c_4.csv", 5))
print(model8.run("juneJuly_c_8.csv", 5))
print(model8.run("juneJuly_c_12.csv", 5))